using DotPudica.Core.Binding;
using DotPudica.Godot.Binding.ControlProxies;
using Godot;

namespace DotPudica.Godot;

/// <summary>
/// Godot control binding proxy factory. Automatically creates corresponding ITargetProxy based on control type and property name.
/// Code generated by Source Generator creates proxies through this factory.
/// </summary>
public static class GodotTargetProxyFactory
{
    private static readonly Dictionary<Type, Func<Control, string, string?, ITargetProxy>> _customFactories = new();

    /// <summary>
    /// Register custom control proxy factory.
    /// </summary>
    public static void Register<TControl>(Func<TControl, string, string?, ITargetProxy> factory)
        where TControl : Control
    {
        _customFactories[typeof(TControl)] = (ctrl, prop, evt) => factory((TControl)ctrl, prop, evt);
    }

    /// <summary>
    /// Create binding proxy for specified control.
    /// </summary>
    /// <param name="control">Godot control</param>
    /// <param name="targetProperty">Target property name</param>
    /// <param name="changeSignal">Change signal name (used for TwoWay)</param>
    public static ITargetProxy Create(Control control, string targetProperty, string? changeSignal)
    {
        // Check custom factories first
        if (_customFactories.TryGetValue(control.GetType(), out var factory))
        {
            return factory(control, targetProperty, changeSignal);
        }

        // Built-in control proxies
        return control switch
        {
            Label label => new LabelProxy(label),
            RichTextLabel richLabel => new RichTextLabelProxy(richLabel,
                targetProperty.Equals("BbcodeText", StringComparison.OrdinalIgnoreCase)),
            LineEdit lineEdit => new LineEditProxy(lineEdit),
            TextEdit textEdit => new TextEditProxy(textEdit),
            SpinBox spinBox => new SpinBoxProxy(spinBox),
            CheckBox checkBox => new CheckBoxProxy(checkBox),
            CheckButton checkButton => new CheckBoxProxy(checkButton),
            OptionButton optionButton => new OptionButtonProxy(optionButton),
            ProgressBar progressBar => new ProgressBarProxy(progressBar),
            TextureRect textureRect => new TextureRectProxy(textureRect),
            Slider slider => new SliderProxy(slider),

            // Generic fallback: use reflection proxy
            _ => new ReflectionProxy(control, targetProperty, changeSignal)
        };
    }

    /// <summary>
    /// Infer default target property name based on control type. Used by Source Generator when TargetProperty is not specified.
    /// </summary>
    public static string InferTargetProperty(Control control) => control switch
    {
        Label => "Text",
        RichTextLabel => "Text",
        LineEdit => "Text",
        TextEdit => "Text",
        SpinBox => "Value",
        CheckBox or CheckButton => "ButtonPressed",
        OptionButton => "Selected",
        ProgressBar => "Value",
        TextureRect => "Texture",
        Slider => "Value",
        _ => "Text"
    };

    /// <summary>
    /// Infer default change signal name based on control type. Used by Source Generator when SourceEvent is not specified.
    /// </summary>
    public static string? InferChangeSignal(Control control) => control switch
    {
        LineEdit => "text_changed",
        TextEdit => "text_changed",
        SpinBox => "value_changed",
        CheckBox or CheckButton => "toggled",
        OptionButton => "item_selected",
        Slider => "value_changed",
        _ => null
    };
}

/// <summary>
/// Reflection-based generic control proxy. Used as fallback when no dedicated proxy exists.
/// </summary>
internal class ReflectionProxy : ITargetProxy
{
    private readonly Control _control;
    private readonly string _propertyName;
    private readonly string? _changeSignal;
    private readonly Callable? _callable;
    private bool _disposed;
    public Type TargetType { get; }
    public event EventHandler? ValueChanged;

    public ReflectionProxy(Control control, string propertyName, string? changeSignal)
    {
        _control = control;
        _propertyName = propertyName;
        _changeSignal = changeSignal;

        var prop = control.GetType().GetProperty(propertyName);
        TargetType = prop?.PropertyType ?? typeof(object);

        if (changeSignal != null)
        {
            _callable = Callable.From(() => ValueChanged?.Invoke(this, EventArgs.Empty));
            _control.Connect(changeSignal, _callable.Value);
        }
    }

    public object? GetValue()
    {
        var prop = _control.GetType().GetProperty(_propertyName);
        return prop?.GetValue(_control);
    }

    public void SetValue(object? value)
    {
        var prop = _control.GetType().GetProperty(_propertyName);
        if (prop?.CanWrite == true)
        {
            prop.SetValue(_control, value);
        }
    }

    public void Dispose()
    {
        if (_disposed)
            return;

        if (_callable.HasValue
            && _changeSignal != null
            && _control.IsConnected(_changeSignal, _callable.Value))
        {
            _control.Disconnect(_changeSignal, _callable.Value);
        }

        ValueChanged = null;
        _disposed = true;
    }
}
